### ISSUE TITLE
Uygulamanın yerelde Vagrant ile çalıştırılabilmesini sağla

### ISSUE THREAD

**Issue by sinansahin** [omu/tbs#14]
Projenin geliştirilmesi sürecinde ekip dışından gelen pull requestler bence baya önemlidir. En azından ubs api olmadan localde proje nasıl çalıştırılabilir bununla ilgili bir doküman yazarsanız süper olur :)

**Comment by roktas** [comment]
Lokalde Vagrant ile çalışacaksınız, iş akışları oturduğunda.   Zamanı gelince...  "Dokümantasyon eksikliği" çok ucu açık bir iş kaydı, başlığı değiştiriyorum.

**Comment by mrdmr** [comment]
session_controller.rb'de 8. satırdaki kontrolü false yaptıktan sonra seed dosyasındaki admin bilgileriyle giriş yapabilirsin @sinansahin
