### ISSUE TITLE
Etkinlik onay aşamalarında hata

### ISSUE THREAD

**Issue by sinansahin** [omu/tbs#24]
Akademik danışman veya SKSAdmin etkinlik isteği için onayla dediğinde bu etkinlik için önceki event_response kayıtları kontrol edilmeli. Kodda kavrayamadığım bölümler olduğundan fixleyip pr yapamıyorum.

```
  def create
    @event_response = EventResponse.new(event_response_params)
    # authorize @event_response
    @event = Event.find(event_response_params['event_id'])
    if @event_response.save
      @event.update(event_status_id: event_response_params['event_status_id'].to_i)
      if event_response_params['event_status_id'] == '5'
        @event.club_period.club.club_category.vocational_club? ? event_response_and_send_mail(@event, 8) : event_response_and_send_mail(@event, 1)
      elsif event_response_params['event_status_id'] == '7'
        event_response_and_send_mail(@event, 1)
      end
      flash.now[:error] = 'Başarılı'
    else
      flash.now[:error] = 'Başarısız'
    end
    redirect_to :back
  end
```

![screenshot from 2017-02-15 14-16-57](https://cloud.githubusercontent.com/assets/9765995/22973362/44eb3a1c-f375-11e6-82cf-c7b59e50521c.png)

**Comment by sinansahin** [comment]
Yukarıdaki aynı etkinlik için etkinlik onay son durumu "SKS Admin Onayı Bekliyor" olmasına rağmen event#show daki görümünü **onaylanmadı** gözüküyor.

![screenshot from 2017-02-15 15-45-30](https://cloud.githubusercontent.com/assets/9765995/22974940/8f4280aa-f37c-11e6-8682-9877e90f6140.png)

**Comment by mrdmr** [comment]
Şu an düzelmiş olması lazım @sinansahin. Dener misin?

**Comment by sinansahin** [comment]
şuan onaylandı gözüküyor, tamamdır :+1:

**Comment by sinansahin** [comment]
yanlız bu issue için 2. comment deki olayı çözüldü de 1. commentteki durumunda fix lenmesi gerekiyor. Formdan kullanıcı onayla dediğinde o kullanıcının rolüne göre o event'in son event_response değeri kontrol edilmeli. Örneğin akademik danışman onayla butonuna bastı ve create fonksiyonu çalıştı, sayfa yeniden yüklenene kadar bir daha onayla butonuna basarsa yeniden create durumu oluşuyor. O yüzden kod aşağıdaki gibi düzenlenmelidir(Mantık/kod hatalı olabilir).

```
......
@event = Event.find(event_response_params['event_id'])
unless @event.event_status_id == event_response_params['event_status_id'].to_i
     if @event_response.save
     ...........      
     end
else 
      "Daha önce onayladığına dair hata mesajı"
end
```

**Comment by mrdmr** [comment]
Bu bi hata değil aslında. İşleyişe engel olmuyor yanlış anlamadıysam. Yine de fazladan tıklayanlar için bir kontrol eklenebilir.

**Comment by roktas** [comment]
Bu standart bir problem, "mükerrer tıklamalardan kaynaklanabilecek sorunlar".  Kendiniz bir çözüm icat etmeden önce Rails'In imkanlarını araştırın veya SO'da arayın.  (Muhtemelen bir UX problemi, sadece kullanıcıyı ekstra bilgilendirmek yeterli olabilir).
