### ISSUE TITLE
Kayıt silinmesi durumu  

### ISSUE THREAD

**Issue by sinansahin** [omu/tbs#27]
Yaşanmış bir problem: Siber güvenlik topluluğu bir etkinlik başvuru oluşturuyor. Akademik danışman onayladıktan sonra rolü SKS Admin olan kullanıcılardan birisi bu kayıtı siliyor(Daha doğrusu kimin sildiği bilinmiyor). 

Kayıtların hiç bir şekilde silinmemesi veya silinen kayıtın log'u bir şekilde admin arayüzünde listelenebilir olmalıdır. 

Ayrıca SKS Admin rolünün yetkileri parçalanabilir. SKSDB'de sadece etkinlik başvurularının çıktısı alan görevli çalışana diğer yetkilerin verilmesi ne kadar mantıklı? sorusuna cevap verebiliyorsak tamam ama verilemiyorsa bu durum ilerde sistemin amacının gerçekleşmesine olumsuz etki sağlayabilir.

**Comment by isubas** [comment]
@sinansahin iş kayıtların için teşekkür ederiz. :clap:

Proje kurgusu daha önceden yapıldığı için ihtiyaç duyulan bazı geliştirmeler zaman alıyor. Proje yapılırken bazı opsiyonların düşünülmemesi ve yapının sürdürülebilir bir şekilde hazırlanmamasından kaynaklı sorunlar yaşıyoruz. Bundan dolayı geliştirmeler hem içimize sinmiyor hemde yavaş oluyor. 

Projenin hızlı bir şekilde geliştirilebilmesi için projenin başlatıcısı olarak senden de katkılar bekliyoruz. Verdiğin ve vereceğin katkılar için şimdiden teşekkür ederiz. :+1:

**Comment by sinansahin** [comment]
İş ve okul dışındaki müsait zamanlarımda elimden geldiğince destek olmaya çalışıyorum ve çalışmaya devam edeceğim :)

_Proje yapılırken bazı opsiyonların düşünülmemesi ve yapının sürdürülebilir bir şekilde hazırlanmamasından kaynaklı sorunlar yaşıyoruz._

Bu durumuna sebebiyet veren kişi aslında benim o yüzden daha fazla destek olmaya çalışıyorum.
