### ISSUE TITLE
Profil Güncellemede Parola Sorunu

### ISSUE THREAD

**Issue by ileri** [omu/tbs#35]
Profil düzenleme alanında Fotoğraf ekleme ve parola değiştirme bölümünde (soldaki bölüm) değişiklikleri kaydetmek için geçerli parola isteniyor, sisteme giriş yaparken girilen UBS parolası oraya yazıldığında hatalı parola uyarısı veriyor.

**Comment by sinansahin** [comment]
Öğrenciler için parola güncelleme alanı disable edilmeli.

**Comment by ileri** [comment]
[f33a76f](https://github.com/omu/tbs/commit/f33a76ffb329ff7e7b91c06f09007d411ac995e8) kodlu commit ile düzeltilmiş.

**Comment by ileri** [comment]
Parola güncelleme alanı kaldırılmasına rağmen fotoğraf değişikliği yapılmak istendiğinde sistem mevcut parolayı doğrulamaya devam ettiği için hata oluşmasına neden oluyor.
