### ISSUE TITLE
Başka Toplulukta Etkinlik Oluştur Linki

### ISSUE THREAD

**Issue by ileri** [omu/tbs#38]
Topluluk yetkilisi kendi topluluk sayfasında "Etkinlik Oluştur" linkini görüyor , ancak diğer topluluklarda da aynı link çıkıyor. Her ne kadar kendi topluluğu için etkinlik oluşturuyor olsa da karışıklığa neden oluyor.

**Comment by demir** [comment]
#46

**Comment by demir** [comment]
#46
