### ISSUE TITLE
Topluluk Dışı Üye İletişim Bilgileri Düzenlenebiliyor

### ISSUE THREAD

**Issue by ileri** [omu/tbs#39]
Başkan kendi topluluğuna üye olmayan başka topluluğa üye olmuş bir kişinin de iletişim bilgilerini düzenleme yetkisine sahip (sanırım, en azından düzenleme butonu görünüyor ve tıklayınca düzenleme pencereciği açılıyor, düzenlemeyi denemedim).

**Comment by demir** [comment]
Çözüm tarafında da katkılarını bekliyoruz @ileri :)
