### ISSUE TITLE
Öğretim Üyesi Giriş Yapamıyor

### ISSUE THREAD

**Issue by ileri** [omu/tbs#40]
Sisteme kayıtlı öğretim üyesi , akademik danışman ( Recai Oktaş ) sisteme giriş yapmak istediğinde Giriş butonuna bastıktan sonra aşağıdaki klasik rails hatası ile karşılaşıyor:

> We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by sinansahin** [comment]
Recai hocanın hesabına veya OYAK topluluğu ayarlarına özel bir durumdan kaynaklı olabilir. Diğer topluluklardan buna yönelik bir bildirim gelmedi henüz. Hatta siber güvenlik topluluğu akademik danışmanı giriş yaptığı ve mobilde etkinlik onayı butonları gozukmedigini bildirdi, bu durumu inceleyip issue açacağım. Özetle pazartesi loglara bakalım.

**Comment by ileri** [comment]
Aynı sorun benim hesabımda da ( ÖYAK Başkanı , öğrenci ) ortaya çıktı. Sisteme giriş yapamıyorum.

**Comment by sinansahin** [comment]
Evet genel bir login problemi var gibi gözüküyor.

**Comment by sinansahin** [comment]
Uygulamanın çalıştığı makine dns çözümlemesi yapamadığı için ubs servisine bağlanamamış dolayısıyla hata veriyordu. Problem giderildi. Issue kapatılabilir.

**Comment by huseyin** [comment]
@sinansahin :+1:

**Comment by roktas** [comment]
Bu hatalar tekrar edebilir.  Adres çözümleme hatasını yakalayıp "hata bize ait değil" esprili uygun bir hata ekranıyla kullanıcıyı bilgilendirin aksi halde fatura uygulamaya kesilir.  Unutmayın programlamanın neredeyse yarısı "hata yönetimi"nden ibarettir.

**Comment by roktas** [comment]
Bir de çok minör durum olmadığı sürece hatayı maintainer kapatsın, bu durumda @sinansahin.

**Comment by roktas** [comment]
Hata yönetimi için şuradan başlayın: https://github.com/omu/tbs/blob/cedff2579791961f6ec791e861b972c724afca79/app/services/ubs.rb#L93

İpuçları:

- https://stackoverflow.com/questions/11423068/how-to-handle-exceptions-with-ruby-rest-client
- http://www.rubydoc.info/gems/rest-client/

Genel ilke: hatalar alt seviyede yakalanır, üst seviyede işlenir.  Exception'ları kontrol edin, üretilen exception'ı aşağıda yakalayıp üst katmanlara ileterek gereğini yapın.

**Comment by ileri** [comment]
Aynı sorun tekrarlamış, girişlerde 500 hatası alınıyor.

**Comment by sinansahin** [comment]
resolv.conf dosyası güncellendi, şuan çalışıyor olması gerekiyor.

@roktas hocam bu makine bu sorunu tekrarladı. Bu ilerde yine tekrarlayacağı anlamına gelebilir. Tekrarlanmaması için makine de nasıl konfigürasyon yapmalıyız ?

**Comment by roktas** [comment]
> Tekrarlanmaması için makine de nasıl konfigürasyon yapmalıyız ?

bu sorunu fırsat bilerek araştırıp öğrenseniz nasıl olur?

**Comment by huseyin** [comment]
bu sorunun ilerde tekrarlaması makinenin reboot edilmesine/edilmemesine bağlı. olay şu. unix sistemlerde  (buna linux ve linux tabanlı dağıtımları da katalım) dns daemon'lar tarafından dinamik olarak yönetilir. mesela masaüstü ortamda debian üzerinden gidersek bunu network manager [1] (sunucu ortamında kim yapar bakmak lazım) dolayısıyla her reboot'da dns overwrite edilir. harici olarak üzerine yazmak bir şey değiştirmez.

burada "keep changes" olayına odaklanıp  doğrudan bunu yapan şeylere bakmak lazım deyip topu ortaya atayım :wink: 

[1] https://wiki.debian.org/NetworkManager

**Comment by sinansahin** [comment]
![1505286082485 remmina-2017-11-13-6 52 34 485100](https://user-images.githubusercontent.com/9765995/32713031-796e6026-c858-11e7-9450-b38045c8fc97.png)

resimde görülen güncelleme yapıldı. Makine reboot edilerek test edildi. Sonuç olarak yapılan konfigürasyon başarılı gözükmektedir.

**Comment by huseyin** [comment]
Eline sağlık @sinansahin sadece resolvconf(8) manual'inde `resolvconf/resolv.conf.d/{base,head,tail}` gibi birşey dikkatimi çekti. detaylı bakmadım fakat ilk düşündüğüm, acaba interface'in altına değil de nameserver'ları buraya mı koymak gerekiyor? gibi bir şey. bu konuda okuduğun kaynaklarda gözüne ilişen bir şey oldu mu?

**Comment by sinansahin** [comment]
@huseyin evet dns tanımlamalarını `resolvconf` ile yapılıyormuş. Ben üstteki ayarı `resolvconf` olmadığını varsayarak yapmıştım daha doğrusu bilmiyordum. 

Daha öncesinde dns tanımları resolvconf/resolv.conf.d/original dosyasına yazılmış. ordan kayıtları resolvconf/resolv.conf.d/base dosyasına taşıdım. interface'deki eklediklerimi de kaldırıp reboot ettim şuan çalışıyor.
![screen shot 2017-11-16 at 19 45 47](https://user-images.githubusercontent.com/9765995/32904021-811cf86c-cb07-11e7-9b61-55d488ba3945.png)
