### ISSUE TITLE
Topluluğa üyelik iş akışında güncelleme

### ISSUE THREAD

**Issue by sinansahin** [omu/tbs#41]
Öğrenci toplulukları yönergesi değiştiği için acil bir şekilde topluluğa üyelik iş akışının güncellenmesi gerekiyor. 

Yeni iş akışı:
- Öğrenci sisteme giriş yapıp ilgili topluluk sayfasına gider. 
- Topluluğa üye ol butonuna tıkladıktan sonra yeni bir sayfada öğrencinin temel bilgileri ve toplulugun adının bulunduğu bir form karşılar. Üyelik şartlarını kabul ediyorum diye bir checkbox olacak formda. Form submit olduğunda kullanıcı topluluğa üye olacak ama durumu pasif olacak. 
- Öğrenci üyelik formunu çıktı alıp ıslak imzalı şekilde topluluk başkanina teslim edecek.
- Başkan yönetim kurulu kararı ile üyeliği aktif hale getirecek veya üyeliğin reddi için açıklama girecek. 
- Üyeliğin reddine itiraz eden öğrenci sksadmin yetkili kullanıcı tarafından üyelik durumu aktif edilebilir veya gerekçe girilerek pasif durumda kalması sağlanabilecek.

**Comment by sinansahin** [comment]
Şuan sistemde üyeler kulübün aktif dönemine üye olmuş gözüküyor. Production ortamında 2016-2017 akademik dönemi hala aktif durumda olup yeni dönem tanımladığımızda tüm üyeler, başkan ve danışmanlar yetkisiz duruma düşecektir. 

Role modeline 3 yeni alan ekleyip yeni yönergeye göre sistemi düzenleyeceğiz. 
Alanlar: `club_id, membership_start_date, membership_end_date`

Üye ve akademik danışman sorgulamasında `club_id` alanını başkan sorgulamasında `club_period_id` alanını kullanacağız. Üyelik başlangıç ve bitiş tarihleri sayesinde [ilgili yönergenin](http://sks.omu.edu.tr/sites/sks.omu.edu.tr/files/files/%C3%96%C4%9Fr_Topluluklar%C4%B1%20Y%C3%B6nergesi%20(SON%20HAL%C4%B0)(1).pdf) madde 17/4 ve madde 18'in uygulanmasında kullanılması planlanmaktadır. 

Ayrıca `black_list` modeli devre dışı kalacağından silinmesi uygundur. 
Role modelindeki `appointment_date` alanı ve `membership_start_date` alanı aynı bilgiyi tutacağından `appointment_date` alanı kaldırılabilir.

**Comment by tulino** [comment]
Üyelik formu gönderen bir kullanıcının durmunun onaylanması admin tarafından yapılamıyor.(buna ait admin tarafında bir view bulunmalı)
Eğer kulubun bir başkanı yoksa admin başkan ataması yapamıyor yukardaki sebepten dolayı.
Terminalden üyeyi aktif hale getirdiğimiz halde üye listesinde listelenemiyor.
