### ISSUE TITLE
Profil Resmi Başka Profillerde de Oturum Açan Kullanıcının Profil Resmi Olarak Görünüyor

### ISSUE THREAD

**Issue by ileri** [omu/tbs#56]
Bir kullanıcı oturum açtığında başka bir kullanıcının profiline bakarken baktığı kullanıcının avatarı yerine kendi avatarı görünüyor.

Karşıklık şu satırdaki koddan kaynaklanıyor.

https://github.com/omu/tbs/blob/517da943196028199232fd93da57a18bd987cfb5/app/views/profiles/show.html.erb#L19

Şu an repoyu canlı olarak deneyemediğim için tam çözümü commitleyemiyorum ancak;

Muhtemelen `current_user` yerine `@profile` ( yada `@profile` ın sahibi olan `user` ı belirten kod parçacığı ) yazılırsa sorun düzelecektir.

**Comment by demir** [comment]
Güncelleme yapacağım az sonra @ileri
