### ISSUE TITLE
Üye Olunan Topluluk Sayısı Sınırı

### ISSUE THREAD

**Issue by ileri** [omu/tbs#59]
**Ondokuz Mayıs Üniversitesi Öğrenci Toplulukları Yönergesi** ( en son yayınlanan hali: 18.09.2017 ) **Dördüncü Bölüm Madde 17 nin 5. bendinde** 
> (5) Bir öğrenci en fazla dört topluluğa üye olabilir, ancak birden fazla topluluğun yönetim ve
denetim kurulunda görev alamaz.

deniliyor.
Ancak üyeler arasında dolaşırken bir öğrencinin 10 dan fazla topluluğa üye olduğunu gördüm.
TBS sisteminde kaç topluluğa üye olunabileceği ile ilgili kısıtlama sağlayacak bir kod var mı yok mu diye kontrol etmedim, ancak sistemin şu anki hali Yönergenin bu maddesini ihlal etmeye açık halde.

Yönerge Linki: http://sks.omu.edu.tr/sites/sks.omu.edu.tr/files/files/%C3%96%C4%9Fr_Topluluklar%C4%B1%20Y%C3%B6nergesi%20(SON%20HAL%C4%B0)(1).pdf

**Comment by demir** [comment]
Şu an bununla ilgili bir düzenleme yok @ileri. Güncelleme çıkaracağız artık.
